---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.upcloud.polarsquad.com
  resources:
  - manageddatabaselogicaldatabases
  - manageddatabases
  - manageddatabaseusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.upcloud.polarsquad.com
  resources:
  - manageddatabaselogicaldatabases/finalizers
  - manageddatabases/finalizers
  - manageddatabaseusers/finalizers
  verbs:
  - update
- apiGroups:
  - database.upcloud.polarsquad.com
  resources:
  - manageddatabaselogicaldatabases/status
  - manageddatabases/status
  - manageddatabaseusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.upcloud.polarsquad.com
  resources:
  - networks
  - routers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.upcloud.polarsquad.com
  resources:
  - networks/finalizers
  - routers/finalizers
  verbs:
  - update
- apiGroups:
  - network.upcloud.polarsquad.com
  resources:
  - networks/status
  - routers/status
  verbs:
  - get
  - patch
  - update
