---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.upcloud.polarsquad.com
  resources:
  - manageddatabaselogicaldatabases
  - manageddatabases
  - manageddatabaseusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.upcloud.polarsquad.com
  resources:
  - manageddatabaselogicaldatabases/finalizers
  - manageddatabases/finalizers
  - manageddatabaseusers/finalizers
  verbs:
  - update
- apiGroups:
  - database.upcloud.polarsquad.com
  resources:
  - manageddatabaselogicaldatabases/status
  - manageddatabases/status
  - manageddatabaseusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.upcloud.polarsquad.com
  resources:
  - gatewayconnections
  - gateways
  - gatewaytunnels
  - networks
  - routers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.upcloud.polarsquad.com
  resources:
  - gatewayconnections/finalizers
  - gateways/finalizers
  - gatewaytunnels/finalizers
  - networks/finalizers
  - routers/finalizers
  verbs:
  - update
- apiGroups:
  - network.upcloud.polarsquad.com
  resources:
  - gatewayconnections/status
  - gateways/status
  - gatewaytunnels/status
  - networks/status
  - routers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - objectstorage.upcloud.polarsquad.com
  resources:
  - managedobjectstorages
  - objectstorageaccesskeys
  - objectstoragebuckets
  - objectstoragecustomdomains
  - objectstoragepolicies
  - objectstorageusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - objectstorage.upcloud.polarsquad.com
  resources:
  - managedobjectstorages/finalizers
  - objectstorageaccesskeys/finalizers
  - objectstoragebuckets/finalizers
  - objectstoragecustomdomains/finalizers
  - objectstoragepolicies/finalizers
  - objectstorageusers/finalizers
  verbs:
  - update
- apiGroups:
  - objectstorage.upcloud.polarsquad.com
  resources:
  - managedobjectstorages/status
  - objectstorageaccesskeys/status
  - objectstoragebuckets/status
  - objectstoragecustomdomains/status
  - objectstoragepolicies/status
  - objectstorageusers/status
  verbs:
  - get
  - patch
  - update
