apiVersion: database.upcloud.polarsquad.com/v1alpha1
kind: ManagedDatabaseUser
metadata:
  labels:
    app.kubernetes.io/name: uck
    app.kubernetes.io/managed-by: kustomize
  name: manageddatabaseuser-sample
spec:
  serviceRef:
    name: manageddatabase-sample
  username: sampleuser
