apiVersion: database.upcloud.polarsquad.com/v1alpha1
kind: ManagedDatabase
metadata:
  labels:
    app.kubernetes.io/name: uck
    app.kubernetes.io/managed-by: kustomize
  name: manageddatabase-sample
spec:
  type: pg
  plan: 1x1xCPU-2GB-25GB
  zone: fi-hel1
  properties:
    version: "16"
  networks:
    - name: private
      type: private
      networkRef:
        name: network-sample
