## Append samples of your project ##
resources:
- network_v1alpha1_network.yaml
- network_v1alpha1_router.yaml
- database_v1alpha1_manageddatabase.yaml
- database_v1alpha1_manageddatabaseuser.yaml
- database_v1alpha1_manageddatabaselogicaldatabase.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
