## Append samples of your project ##
resources:
- network_v1alpha1_network.yaml
- network_v1alpha1_router.yaml
- network_v1alpha1_gateway.yaml
- network_v1alpha1_gatewayconnection.yaml
- network_v1alpha1_gatewaytunnel.yaml
- network_v1alpha1_vpn-psk-secret.yaml
- database_v1alpha1_manageddatabase.yaml
- database_v1alpha1_manageddatabaseuser.yaml
- database_v1alpha1_manageddatabaselogicaldatabase.yaml
- objectstorage_v1alpha1_managedobjectstorage.yaml
- objectstorage_v1alpha1_objectstoragepolicy.yaml
- objectstorage_v1alpha1_objectstorageuser.yaml
- objectstorage_v1alpha1_objectstorageaccesskey.yaml
- objectstorage_v1alpha1_objectstoragebucket.yaml
- objectstorage_v1alpha1_objectstoragecustomdomain.yaml
- loadbalancer_v1alpha1_loadbalancer.yaml
- loadbalancer_v1alpha1_loadbalancerbackend.yaml
- loadbalancer_v1alpha1_loadbalancerbackendmember.yaml
- loadbalancer_v1alpha1_loadbalancerbackendtlsconfig.yaml
- loadbalancer_v1alpha1_loadbalancerresolver.yaml
- loadbalancer_v1alpha1_loadbalancerfrontend.yaml
- loadbalancer_v1alpha1_loadbalancerfrontendrule.yaml
- loadbalancer_v1alpha1_loadbalancerfrontendtlsconfig.yaml
- loadbalancer_v1alpha1_loadbalancercertificatebundle.yaml
- loadbalancer_v1alpha1_lb-sample-tls.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
