apiVersion: loadbalancer.upcloud.polarsquad.com/v1alpha1
kind: LoadBalancerFrontendTLSConfig
metadata:
  labels:
    app.kubernetes.io/name: uck
    app.kubernetes.io/managed-by: kustomize
  name: loadbalancerfrontendtlsconfig-sample
spec:
  frontendRef:
    name: loadbalancerfrontend-sample
  name: tls-web
  certificateBundleRef:
    name: loadbalancercertificatebundle-sample
