apiVersion: network.upcloud.polarsquad.com/v1alpha1
kind: Network
metadata:
  labels:
    app.kubernetes.io/name: uck
    app.kubernetes.io/managed-by: kustomize
  name: network-sample
spec:
  zone: fi-hel1
  ipNetworks:
    - address: 10.1.0.0/24
      dhcp: true
  routerRef:
    name: router-sample
