apiVersion: network.upcloud.polarsquad.com/v1alpha1
kind: Router
metadata:
  labels:
    app.kubernetes.io/name: upcloud-operator
    app.kubernetes.io/managed-by: kustomize
  name: router-sample
spec:
  staticRoutes:
    - name: to-office
      route: 10.9.0.0/16
      nexthop: 10.0.0.1
  labels:
    env: demo
