apiVersion: objectstorage.upcloud.polarsquad.com/v1alpha1
kind: ManagedObjectStorage
metadata:
  labels:
    app.kubernetes.io/name: upcloud-operator
    app.kubernetes.io/managed-by: kustomize
  name: managedobjectstorage-sample
spec:
  region: fi-hel1
  networks:
    - name: public
      type: public
