apiVersion: objectstorage.upcloud.polarsquad.com/v1alpha1
kind: ObjectStorageCustomDomain
metadata:
  labels:
    app.kubernetes.io/name: upcloud-operator
    app.kubernetes.io/managed-by: kustomize
  name: objectstoragecustomdomain-sample
spec:
  serviceRef:
    name: managedobjectstorage-sample
  domainName: objects.example.com
  type: public
