//go:build !ignore_autogenerated

/*
Copyright 2026 Polar Squad.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/polarsquad/upcloud-operator/api/common"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionHTTPRedirect) DeepCopyInto(out *ActionHTTPRedirect) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionHTTPRedirect.
func (in *ActionHTTPRedirect) DeepCopy() *ActionHTTPRedirect {
	if in == nil {
		return nil
	}
	out := new(ActionHTTPRedirect)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionHTTPReturn) DeepCopyInto(out *ActionHTTPReturn) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionHTTPReturn.
func (in *ActionHTTPReturn) DeepCopy() *ActionHTTPReturn {
	if in == nil {
		return nil
	}
	out := new(ActionHTTPReturn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionHTTPRewritePath) DeepCopyInto(out *ActionHTTPRewritePath) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionHTTPRewritePath.
func (in *ActionHTTPRewritePath) DeepCopy() *ActionHTTPRewritePath {
	if in == nil {
		return nil
	}
	out := new(ActionHTTPRewritePath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionHTTPRewriteURI) DeepCopyInto(out *ActionHTTPRewriteURI) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionHTTPRewriteURI.
func (in *ActionHTTPRewriteURI) DeepCopy() *ActionHTTPRewriteURI {
	if in == nil {
		return nil
	}
	out := new(ActionHTTPRewriteURI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionSetHeader) DeepCopyInto(out *ActionSetHeader) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionSetHeader.
func (in *ActionSetHeader) DeepCopy() *ActionSetHeader {
	if in == nil {
		return nil
	}
	out := new(ActionSetHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionUseBackend) DeepCopyInto(out *ActionUseBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionUseBackend.
func (in *ActionUseBackend) DeepCopy() *ActionUseBackend {
	if in == nil {
		return nil
	}
	out := new(ActionUseBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrontendNetwork) DeepCopyInto(out *FrontendNetwork) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrontendNetwork.
func (in *FrontendNetwork) DeepCopy() *FrontendNetwork {
	if in == nil {
		return nil
	}
	out := new(FrontendNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LBStatusNetwork) DeepCopyInto(out *LBStatusNetwork) {
	*out = *in
	if in.IPAddresses != nil {
		in, out := &in.IPAddresses, &out.IPAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LBStatusNetwork.
func (in *LBStatusNetwork) DeepCopy() *LBStatusNetwork {
	if in == nil {
		return nil
	}
	out := new(LBStatusNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancer) DeepCopyInto(out *LoadBalancer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancer.
func (in *LoadBalancer) DeepCopy() *LoadBalancer {
	if in == nil {
		return nil
	}
	out := new(LoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerBackend) DeepCopyInto(out *LoadBalancerBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerBackend.
func (in *LoadBalancerBackend) DeepCopy() *LoadBalancerBackend {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerBackendList) DeepCopyInto(out *LoadBalancerBackendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancerBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerBackendList.
func (in *LoadBalancerBackendList) DeepCopy() *LoadBalancerBackendList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerBackendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerBackendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerBackendMember) DeepCopyInto(out *LoadBalancerBackendMember) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerBackendMember.
func (in *LoadBalancerBackendMember) DeepCopy() *LoadBalancerBackendMember {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerBackendMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerBackendMember) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerBackendMemberList) DeepCopyInto(out *LoadBalancerBackendMemberList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancerBackendMember, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerBackendMemberList.
func (in *LoadBalancerBackendMemberList) DeepCopy() *LoadBalancerBackendMemberList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerBackendMemberList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerBackendMemberList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerBackendMemberSpec) DeepCopyInto(out *LoadBalancerBackendMemberSpec) {
	*out = *in
	out.BackendRef = in.BackendRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerBackendMemberSpec.
func (in *LoadBalancerBackendMemberSpec) DeepCopy() *LoadBalancerBackendMemberSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerBackendMemberSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerBackendMemberStatus) DeepCopyInto(out *LoadBalancerBackendMemberStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerBackendMemberStatus.
func (in *LoadBalancerBackendMemberStatus) DeepCopy() *LoadBalancerBackendMemberStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerBackendMemberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerBackendProperties) DeepCopyInto(out *LoadBalancerBackendProperties) {
	*out = *in
	if in.HealthCheckTLSVerify != nil {
		in, out := &in.HealthCheckTLSVerify, &out.HealthCheckTLSVerify
		*out = new(bool)
		**out = **in
	}
	if in.TLSEnabled != nil {
		in, out := &in.TLSEnabled, &out.TLSEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TLSVerify != nil {
		in, out := &in.TLSVerify, &out.TLSVerify
		*out = new(bool)
		**out = **in
	}
	if in.TLSUseSystemCA != nil {
		in, out := &in.TLSUseSystemCA, &out.TLSUseSystemCA
		*out = new(bool)
		**out = **in
	}
	if in.HTTP2Enabled != nil {
		in, out := &in.HTTP2Enabled, &out.HTTP2Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerBackendProperties.
func (in *LoadBalancerBackendProperties) DeepCopy() *LoadBalancerBackendProperties {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerBackendProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerBackendSpec) DeepCopyInto(out *LoadBalancerBackendSpec) {
	*out = *in
	out.LoadBalancerRef = in.LoadBalancerRef
	if in.ResolverRef != nil {
		in, out := &in.ResolverRef, &out.ResolverRef
		*out = new(common.LocalObjectReference)
		**out = **in
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = new(LoadBalancerBackendProperties)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerBackendSpec.
func (in *LoadBalancerBackendSpec) DeepCopy() *LoadBalancerBackendSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerBackendStatus) DeepCopyInto(out *LoadBalancerBackendStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerBackendStatus.
func (in *LoadBalancerBackendStatus) DeepCopy() *LoadBalancerBackendStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerBackendTLSConfig) DeepCopyInto(out *LoadBalancerBackendTLSConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerBackendTLSConfig.
func (in *LoadBalancerBackendTLSConfig) DeepCopy() *LoadBalancerBackendTLSConfig {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerBackendTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerBackendTLSConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerBackendTLSConfigList) DeepCopyInto(out *LoadBalancerBackendTLSConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancerBackendTLSConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerBackendTLSConfigList.
func (in *LoadBalancerBackendTLSConfigList) DeepCopy() *LoadBalancerBackendTLSConfigList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerBackendTLSConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerBackendTLSConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerBackendTLSConfigSpec) DeepCopyInto(out *LoadBalancerBackendTLSConfigSpec) {
	*out = *in
	out.BackendRef = in.BackendRef
	out.CertificateBundleRef = in.CertificateBundleRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerBackendTLSConfigSpec.
func (in *LoadBalancerBackendTLSConfigSpec) DeepCopy() *LoadBalancerBackendTLSConfigSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerBackendTLSConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerBackendTLSConfigStatus) DeepCopyInto(out *LoadBalancerBackendTLSConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerBackendTLSConfigStatus.
func (in *LoadBalancerBackendTLSConfigStatus) DeepCopy() *LoadBalancerBackendTLSConfigStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerBackendTLSConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerCertificateBundle) DeepCopyInto(out *LoadBalancerCertificateBundle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerCertificateBundle.
func (in *LoadBalancerCertificateBundle) DeepCopy() *LoadBalancerCertificateBundle {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerCertificateBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerCertificateBundle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerCertificateBundleList) DeepCopyInto(out *LoadBalancerCertificateBundleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancerCertificateBundle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerCertificateBundleList.
func (in *LoadBalancerCertificateBundleList) DeepCopy() *LoadBalancerCertificateBundleList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerCertificateBundleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerCertificateBundleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerCertificateBundleSpec) DeepCopyInto(out *LoadBalancerCertificateBundleSpec) {
	*out = *in
	if in.CertificateSecretRef != nil {
		in, out := &in.CertificateSecretRef, &out.CertificateSecretRef
		*out = new(common.LocalObjectReference)
		**out = **in
	}
	if in.Hostnames != nil {
		in, out := &in.Hostnames, &out.Hostnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerCertificateBundleSpec.
func (in *LoadBalancerCertificateBundleSpec) DeepCopy() *LoadBalancerCertificateBundleSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerCertificateBundleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerCertificateBundleStatus) DeepCopyInto(out *LoadBalancerCertificateBundleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerCertificateBundleStatus.
func (in *LoadBalancerCertificateBundleStatus) DeepCopy() *LoadBalancerCertificateBundleStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerCertificateBundleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerFrontend) DeepCopyInto(out *LoadBalancerFrontend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerFrontend.
func (in *LoadBalancerFrontend) DeepCopy() *LoadBalancerFrontend {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerFrontend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerFrontend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerFrontendList) DeepCopyInto(out *LoadBalancerFrontendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancerFrontend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerFrontendList.
func (in *LoadBalancerFrontendList) DeepCopy() *LoadBalancerFrontendList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerFrontendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerFrontendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerFrontendProperties) DeepCopyInto(out *LoadBalancerFrontendProperties) {
	*out = *in
	if in.InboundProxyProtocol != nil {
		in, out := &in.InboundProxyProtocol, &out.InboundProxyProtocol
		*out = new(bool)
		**out = **in
	}
	if in.HTTP2Enabled != nil {
		in, out := &in.HTTP2Enabled, &out.HTTP2Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerFrontendProperties.
func (in *LoadBalancerFrontendProperties) DeepCopy() *LoadBalancerFrontendProperties {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerFrontendProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerFrontendRule) DeepCopyInto(out *LoadBalancerFrontendRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerFrontendRule.
func (in *LoadBalancerFrontendRule) DeepCopy() *LoadBalancerFrontendRule {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerFrontendRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerFrontendRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerFrontendRuleList) DeepCopyInto(out *LoadBalancerFrontendRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancerFrontendRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerFrontendRuleList.
func (in *LoadBalancerFrontendRuleList) DeepCopy() *LoadBalancerFrontendRuleList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerFrontendRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerFrontendRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerFrontendRuleSpec) DeepCopyInto(out *LoadBalancerFrontendRuleSpec) {
	*out = *in
	out.FrontendRef = in.FrontendRef
	if in.Matchers != nil {
		in, out := &in.Matchers, &out.Matchers
		*out = make([]RuleMatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]RuleAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerFrontendRuleSpec.
func (in *LoadBalancerFrontendRuleSpec) DeepCopy() *LoadBalancerFrontendRuleSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerFrontendRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerFrontendRuleStatus) DeepCopyInto(out *LoadBalancerFrontendRuleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerFrontendRuleStatus.
func (in *LoadBalancerFrontendRuleStatus) DeepCopy() *LoadBalancerFrontendRuleStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerFrontendRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerFrontendSpec) DeepCopyInto(out *LoadBalancerFrontendSpec) {
	*out = *in
	out.LoadBalancerRef = in.LoadBalancerRef
	out.DefaultBackendRef = in.DefaultBackendRef
	if in.Networks != nil {
		in, out := &in.Networks, &out.Networks
		*out = make([]FrontendNetwork, len(*in))
		copy(*out, *in)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = new(LoadBalancerFrontendProperties)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerFrontendSpec.
func (in *LoadBalancerFrontendSpec) DeepCopy() *LoadBalancerFrontendSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerFrontendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerFrontendStatus) DeepCopyInto(out *LoadBalancerFrontendStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerFrontendStatus.
func (in *LoadBalancerFrontendStatus) DeepCopy() *LoadBalancerFrontendStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerFrontendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerFrontendTLSConfig) DeepCopyInto(out *LoadBalancerFrontendTLSConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerFrontendTLSConfig.
func (in *LoadBalancerFrontendTLSConfig) DeepCopy() *LoadBalancerFrontendTLSConfig {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerFrontendTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerFrontendTLSConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerFrontendTLSConfigList) DeepCopyInto(out *LoadBalancerFrontendTLSConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancerFrontendTLSConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerFrontendTLSConfigList.
func (in *LoadBalancerFrontendTLSConfigList) DeepCopy() *LoadBalancerFrontendTLSConfigList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerFrontendTLSConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerFrontendTLSConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerFrontendTLSConfigSpec) DeepCopyInto(out *LoadBalancerFrontendTLSConfigSpec) {
	*out = *in
	out.FrontendRef = in.FrontendRef
	out.CertificateBundleRef = in.CertificateBundleRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerFrontendTLSConfigSpec.
func (in *LoadBalancerFrontendTLSConfigSpec) DeepCopy() *LoadBalancerFrontendTLSConfigSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerFrontendTLSConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerFrontendTLSConfigStatus) DeepCopyInto(out *LoadBalancerFrontendTLSConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerFrontendTLSConfigStatus.
func (in *LoadBalancerFrontendTLSConfigStatus) DeepCopy() *LoadBalancerFrontendTLSConfigStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerFrontendTLSConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerList) DeepCopyInto(out *LoadBalancerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerList.
func (in *LoadBalancerList) DeepCopy() *LoadBalancerList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerNetworkAttachment) DeepCopyInto(out *LoadBalancerNetworkAttachment) {
	*out = *in
	if in.NetworkRef != nil {
		in, out := &in.NetworkRef, &out.NetworkRef
		*out = new(common.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerNetworkAttachment.
func (in *LoadBalancerNetworkAttachment) DeepCopy() *LoadBalancerNetworkAttachment {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerNetworkAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerResolver) DeepCopyInto(out *LoadBalancerResolver) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerResolver.
func (in *LoadBalancerResolver) DeepCopy() *LoadBalancerResolver {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerResolver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerResolver) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerResolverList) DeepCopyInto(out *LoadBalancerResolverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancerResolver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerResolverList.
func (in *LoadBalancerResolverList) DeepCopy() *LoadBalancerResolverList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerResolverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerResolverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerResolverSpec) DeepCopyInto(out *LoadBalancerResolverSpec) {
	*out = *in
	out.LoadBalancerRef = in.LoadBalancerRef
	if in.Nameservers != nil {
		in, out := &in.Nameservers, &out.Nameservers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerResolverSpec.
func (in *LoadBalancerResolverSpec) DeepCopy() *LoadBalancerResolverSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerResolverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerResolverStatus) DeepCopyInto(out *LoadBalancerResolverStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerResolverStatus.
func (in *LoadBalancerResolverStatus) DeepCopy() *LoadBalancerResolverStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerResolverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerSpec) DeepCopyInto(out *LoadBalancerSpec) {
	*out = *in
	if in.Networks != nil {
		in, out := &in.Networks, &out.Networks
		*out = make([]LoadBalancerNetworkAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Maintenance = in.Maintenance
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(common.UpCloudLabels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerSpec.
func (in *LoadBalancerSpec) DeepCopy() *LoadBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerStatus) DeepCopyInto(out *LoadBalancerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Networks != nil {
		in, out := &in.Networks, &out.Networks
		*out = make([]LBStatusNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerStatus.
func (in *LoadBalancerStatus) DeepCopy() *LoadBalancerStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Maintenance) DeepCopyInto(out *Maintenance) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Maintenance.
func (in *Maintenance) DeepCopy() *Maintenance {
	if in == nil {
		return nil
	}
	out := new(Maintenance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatcherHTTPMethod) DeepCopyInto(out *MatcherHTTPMethod) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatcherHTTPMethod.
func (in *MatcherHTTPMethod) DeepCopy() *MatcherHTTPMethod {
	if in == nil {
		return nil
	}
	out := new(MatcherHTTPMethod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatcherHost) DeepCopyInto(out *MatcherHost) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatcherHost.
func (in *MatcherHost) DeepCopy() *MatcherHost {
	if in == nil {
		return nil
	}
	out := new(MatcherHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatcherInteger) DeepCopyInto(out *MatcherInteger) {
	*out = *in
	if in.RangeStart != nil {
		in, out := &in.RangeStart, &out.RangeStart
		*out = new(int)
		**out = **in
	}
	if in.RangeEnd != nil {
		in, out := &in.RangeEnd, &out.RangeEnd
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatcherInteger.
func (in *MatcherInteger) DeepCopy() *MatcherInteger {
	if in == nil {
		return nil
	}
	out := new(MatcherInteger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatcherNumMembersUp) DeepCopyInto(out *MatcherNumMembersUp) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatcherNumMembersUp.
func (in *MatcherNumMembersUp) DeepCopy() *MatcherNumMembersUp {
	if in == nil {
		return nil
	}
	out := new(MatcherNumMembersUp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatcherSrcIP) DeepCopyInto(out *MatcherSrcIP) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatcherSrcIP.
func (in *MatcherSrcIP) DeepCopy() *MatcherSrcIP {
	if in == nil {
		return nil
	}
	out := new(MatcherSrcIP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatcherString) DeepCopyInto(out *MatcherString) {
	*out = *in
	if in.IgnoreCase != nil {
		in, out := &in.IgnoreCase, &out.IgnoreCase
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatcherString.
func (in *MatcherString) DeepCopy() *MatcherString {
	if in == nil {
		return nil
	}
	out := new(MatcherString)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatcherStringWithArgument) DeepCopyInto(out *MatcherStringWithArgument) {
	*out = *in
	if in.IgnoreCase != nil {
		in, out := &in.IgnoreCase, &out.IgnoreCase
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatcherStringWithArgument.
func (in *MatcherStringWithArgument) DeepCopy() *MatcherStringWithArgument {
	if in == nil {
		return nil
	}
	out := new(MatcherStringWithArgument)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleAction) DeepCopyInto(out *RuleAction) {
	*out = *in
	if in.UseBackend != nil {
		in, out := &in.UseBackend, &out.UseBackend
		*out = new(ActionUseBackend)
		**out = **in
	}
	if in.HTTPReturn != nil {
		in, out := &in.HTTPReturn, &out.HTTPReturn
		*out = new(ActionHTTPReturn)
		**out = **in
	}
	if in.HTTPRedirect != nil {
		in, out := &in.HTTPRedirect, &out.HTTPRedirect
		*out = new(ActionHTTPRedirect)
		**out = **in
	}
	if in.HTTPRewritePath != nil {
		in, out := &in.HTTPRewritePath, &out.HTTPRewritePath
		*out = new(ActionHTTPRewritePath)
		**out = **in
	}
	if in.HTTPRewriteURI != nil {
		in, out := &in.HTTPRewriteURI, &out.HTTPRewriteURI
		*out = new(ActionHTTPRewriteURI)
		**out = **in
	}
	if in.SetRequestHeader != nil {
		in, out := &in.SetRequestHeader, &out.SetRequestHeader
		*out = new(ActionSetHeader)
		**out = **in
	}
	if in.SetResponseHeader != nil {
		in, out := &in.SetResponseHeader, &out.SetResponseHeader
		*out = new(ActionSetHeader)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleAction.
func (in *RuleAction) DeepCopy() *RuleAction {
	if in == nil {
		return nil
	}
	out := new(RuleAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleMatcher) DeepCopyInto(out *RuleMatcher) {
	*out = *in
	if in.Inverse != nil {
		in, out := &in.Inverse, &out.Inverse
		*out = new(bool)
		**out = **in
	}
	if in.SrcIP != nil {
		in, out := &in.SrcIP, &out.SrcIP
		*out = new(MatcherSrcIP)
		**out = **in
	}
	if in.SrcPort != nil {
		in, out := &in.SrcPort, &out.SrcPort
		*out = new(MatcherInteger)
		(*in).DeepCopyInto(*out)
	}
	if in.BodySize != nil {
		in, out := &in.BodySize, &out.BodySize
		*out = new(MatcherInteger)
		(*in).DeepCopyInto(*out)
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(MatcherString)
		(*in).DeepCopyInto(*out)
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(MatcherString)
		(*in).DeepCopyInto(*out)
	}
	if in.URLQuery != nil {
		in, out := &in.URLQuery, &out.URLQuery
		*out = new(MatcherString)
		(*in).DeepCopyInto(*out)
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(MatcherHost)
		**out = **in
	}
	if in.HTTPMethod != nil {
		in, out := &in.HTTPMethod, &out.HTTPMethod
		*out = new(MatcherHTTPMethod)
		**out = **in
	}
	if in.HTTPStatus != nil {
		in, out := &in.HTTPStatus, &out.HTTPStatus
		*out = new(MatcherInteger)
		(*in).DeepCopyInto(*out)
	}
	if in.Cookie != nil {
		in, out := &in.Cookie, &out.Cookie
		*out = new(MatcherStringWithArgument)
		(*in).DeepCopyInto(*out)
	}
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = new(MatcherStringWithArgument)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestHeader != nil {
		in, out := &in.RequestHeader, &out.RequestHeader
		*out = new(MatcherStringWithArgument)
		(*in).DeepCopyInto(*out)
	}
	if in.ResponseHeader != nil {
		in, out := &in.ResponseHeader, &out.ResponseHeader
		*out = new(MatcherStringWithArgument)
		(*in).DeepCopyInto(*out)
	}
	if in.URLParam != nil {
		in, out := &in.URLParam, &out.URLParam
		*out = new(MatcherStringWithArgument)
		(*in).DeepCopyInto(*out)
	}
	if in.NumMembersUp != nil {
		in, out := &in.NumMembersUp, &out.NumMembersUp
		*out = new(MatcherNumMembersUp)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleMatcher.
func (in *RuleMatcher) DeepCopy() *RuleMatcher {
	if in == nil {
		return nil
	}
	out := new(RuleMatcher)
	in.DeepCopyInto(out)
	return out
}
