//go:build !ignore_autogenerated

/*
Copyright 2026 Polar Squad.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/polarsquad/upcloud-operator/api/common"
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Maintenance) DeepCopyInto(out *Maintenance) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Maintenance.
func (in *Maintenance) DeepCopy() *Maintenance {
	if in == nil {
		return nil
	}
	out := new(Maintenance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedDatabase) DeepCopyInto(out *ManagedDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedDatabase.
func (in *ManagedDatabase) DeepCopy() *ManagedDatabase {
	if in == nil {
		return nil
	}
	out := new(ManagedDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedDatabaseList) DeepCopyInto(out *ManagedDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedDatabaseList.
func (in *ManagedDatabaseList) DeepCopy() *ManagedDatabaseList {
	if in == nil {
		return nil
	}
	out := new(ManagedDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedDatabaseLogicalDatabase) DeepCopyInto(out *ManagedDatabaseLogicalDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedDatabaseLogicalDatabase.
func (in *ManagedDatabaseLogicalDatabase) DeepCopy() *ManagedDatabaseLogicalDatabase {
	if in == nil {
		return nil
	}
	out := new(ManagedDatabaseLogicalDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedDatabaseLogicalDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedDatabaseLogicalDatabaseList) DeepCopyInto(out *ManagedDatabaseLogicalDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedDatabaseLogicalDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedDatabaseLogicalDatabaseList.
func (in *ManagedDatabaseLogicalDatabaseList) DeepCopy() *ManagedDatabaseLogicalDatabaseList {
	if in == nil {
		return nil
	}
	out := new(ManagedDatabaseLogicalDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedDatabaseLogicalDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedDatabaseLogicalDatabaseSpec) DeepCopyInto(out *ManagedDatabaseLogicalDatabaseSpec) {
	*out = *in
	out.ServiceRef = in.ServiceRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedDatabaseLogicalDatabaseSpec.
func (in *ManagedDatabaseLogicalDatabaseSpec) DeepCopy() *ManagedDatabaseLogicalDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedDatabaseLogicalDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedDatabaseLogicalDatabaseStatus) DeepCopyInto(out *ManagedDatabaseLogicalDatabaseStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedDatabaseLogicalDatabaseStatus.
func (in *ManagedDatabaseLogicalDatabaseStatus) DeepCopy() *ManagedDatabaseLogicalDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedDatabaseLogicalDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedDatabaseSpec) DeepCopyInto(out *ManagedDatabaseSpec) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Maintenance != nil {
		in, out := &in.Maintenance, &out.Maintenance
		*out = new(Maintenance)
		**out = **in
	}
	if in.Networks != nil {
		in, out := &in.Networks, &out.Networks
		*out = make([]common.NetworkAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Powered != nil {
		in, out := &in.Powered, &out.Powered
		*out = new(bool)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(common.UpCloudLabels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedDatabaseSpec.
func (in *ManagedDatabaseSpec) DeepCopy() *ManagedDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedDatabaseStatus) DeepCopyInto(out *ManagedDatabaseStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedDatabaseStatus.
func (in *ManagedDatabaseStatus) DeepCopy() *ManagedDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedDatabaseUser) DeepCopyInto(out *ManagedDatabaseUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedDatabaseUser.
func (in *ManagedDatabaseUser) DeepCopy() *ManagedDatabaseUser {
	if in == nil {
		return nil
	}
	out := new(ManagedDatabaseUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedDatabaseUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedDatabaseUserList) DeepCopyInto(out *ManagedDatabaseUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedDatabaseUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedDatabaseUserList.
func (in *ManagedDatabaseUserList) DeepCopy() *ManagedDatabaseUserList {
	if in == nil {
		return nil
	}
	out := new(ManagedDatabaseUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedDatabaseUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedDatabaseUserSpec) DeepCopyInto(out *ManagedDatabaseUserSpec) {
	*out = *in
	out.ServiceRef = in.ServiceRef
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(common.SecretKeySelector)
		**out = **in
	}
	if in.PGAccessControl != nil {
		in, out := &in.PGAccessControl, &out.PGAccessControl
		*out = new(PGUserAccessControl)
		(*in).DeepCopyInto(*out)
	}
	if in.ValkeyAccessControl != nil {
		in, out := &in.ValkeyAccessControl, &out.ValkeyAccessControl
		*out = new(ValkeyUserAccessControl)
		(*in).DeepCopyInto(*out)
	}
	if in.OpenSearchAccessControl != nil {
		in, out := &in.OpenSearchAccessControl, &out.OpenSearchAccessControl
		*out = new(OpenSearchUserAccessControl)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedDatabaseUserSpec.
func (in *ManagedDatabaseUserSpec) DeepCopy() *ManagedDatabaseUserSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedDatabaseUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedDatabaseUserStatus) DeepCopyInto(out *ManagedDatabaseUserStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedDatabaseUserStatus.
func (in *ManagedDatabaseUserStatus) DeepCopy() *ManagedDatabaseUserStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedDatabaseUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchRule) DeepCopyInto(out *OpenSearchRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchRule.
func (in *OpenSearchRule) DeepCopy() *OpenSearchRule {
	if in == nil {
		return nil
	}
	out := new(OpenSearchRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchUserAccessControl) DeepCopyInto(out *OpenSearchUserAccessControl) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]OpenSearchRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchUserAccessControl.
func (in *OpenSearchUserAccessControl) DeepCopy() *OpenSearchUserAccessControl {
	if in == nil {
		return nil
	}
	out := new(OpenSearchUserAccessControl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PGUserAccessControl) DeepCopyInto(out *PGUserAccessControl) {
	*out = *in
	if in.AllowReplication != nil {
		in, out := &in.AllowReplication, &out.AllowReplication
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PGUserAccessControl.
func (in *PGUserAccessControl) DeepCopy() *PGUserAccessControl {
	if in == nil {
		return nil
	}
	out := new(PGUserAccessControl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValkeyUserAccessControl) DeepCopyInto(out *ValkeyUserAccessControl) {
	*out = *in
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Commands != nil {
		in, out := &in.Commands, &out.Commands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValkeyUserAccessControl.
func (in *ValkeyUserAccessControl) DeepCopy() *ValkeyUserAccessControl {
	if in == nil {
		return nil
	}
	out := new(ValkeyUserAccessControl)
	in.DeepCopyInto(out)
	return out
}
